@startuml

package "server" #DDDDDD {
    interface ServerPlayerInterface{
        play1()
        play2()
    }
    class Player1Impl{
        play1()
        play2()
    }
    class Player2Impl{
        play1()
        play2()
    }
    ServerPlayerInterface <|.. Player1Impl
    ServerPlayerInterface <|.. Player2Impl
}

package "client" #DDDDDD {
    interface ClientPlayerInterface{
        play()
    }
    class ClientPlayerImpl{
        play()
    }
    ClientPlayerInterface <|.. ClientPlayerImpl
}
class Adapter{
    play()
}
ClientPlayerInterface <|.down. Adapter
Adapter <-right- ClientPlayerImpl
Player1Impl <-up- Adapter
Player2Impl <-up- Adapter

@enduml